# Generated by Django 5.2.4 on 2025-10-14 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expdate',
        ),
    ]
